# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170610_1604'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfileInfo',
            new_name='UserProfile',
        ),
    ]
