# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170611_0851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='balance',
            new_name='bank_balance',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='bank',
            new_name='betting_balance',
        ),
    ]
